version: '3'

services:
  mysqldb:
    image: mysql
    container_name: "ecom-catalogs-mysqldb"
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
      - MYSQL_ROOT_HOST= %
    volumes:
      - mysql_data:/var/lib/mysql
      
  elasticdb:
    image: elasticsearch:2.4.6
    container_name: "search-server"
    ports:
      - "9200:9200"
      - "9300:9300"
      
  mongodb:
    image: mongo:latest
    container_name: "ecom-reviews-mongodb"
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo_data:/data/db
            
  eureka-server:
    image: doum167/ecom-eureka
    container_name: "server-discovery"
    ports:
     - "8761:8761"
     
  gateway:
    image: doum167/ecom-gateway
    container_name: "server-gateway"
    links:
      - eureka-server
    ports:
      - "9000:8080"

  reviewservice:
    image: doum167/ecom-reviews
    container_name: "ecom-reviews"
    ports:
      - "8280:8080"
    depends_on:
      - mongodb
      - eureka-server
      
  catalogservice:
    image: doum167/ecom-catalogs
    container_name: "ecom-catalogs"
    ports:
      - "8180:8080"
    depends_on:
      - mysqldb
      - eureka-server
      
  searchservice:
    image: doum167/ecom-search
    container_name: "ecom-search"
    ports:
      - "8380:8080"
    entrypoint: ./wait-for-it.sh elasticdb:9300 -t 60 --
    command: java -jar /app.jar
    depends_on:
      - elasticdb
      - eureka-server
         
volumes:
  mongo_data: 
  mysql_data: 