zuul:
  prefix: /api
  routes:
    reviews: 
      path: /reviews/**
      serviceId: reviews-service
    catalogs: 
      path: /cat/**
      serviceId: catalogs-service
    products: 
      path: /prod/**
      serviceId: catalogs-service
    serach:
      path: /search/**
      service-id: search-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8080