version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo_data:/data/db

  reviewservice:
    image: doum167/ecom-reviews
    ports:
      - "8280:8080"
    depends_on:
      - mongodb
      
volumes:
  mongo_data: 